name: cotizaciones_app
description: "Aplicacion de cotizaciones para los hoteles."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  supabase_flutter: ^2.9.1
  url_launcher: ^6.2.6
  flutter_dotenv: ^5.1.0
  intl: ^0.20.2
  uuid: ^3.0.7
  pdf: ^3.10.8
  printing: ^5.12.0
  image_picker: ^0.8.7+4
  http: ^0.13.5
  path_provider: ^2.1.1
  share_plus: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/iconLogo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/ReyPalac.png
    - assets/Madero.png
    - assets/logo.webp
    - .env
    - assets/imgLogin.png
    - assets/welcome.png
    - assets/iconLogo.png
    - assets/fonts/acterum-signature-font.ttf
