name: cotizaciones_app
description: "Aplicacion de cotizaciones para los hoteles."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  supabase_flutter: ^2.9.1
  url_launcher: ^6.2.6
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ReyPalac.png
    - assets/Madero.png
    - assets/logo.webp
    - .env
